# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#build project
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#run tests
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'Lingowords\Lingowords.Test\Lingowords.Test.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Lingowords\Lingowords'
    Contents: '**'
    TargetFolder: 'Lingowords\Lingowords\bin\Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Lingowords\\Lingowords\bin\Release'
    ArtifactName: 'drop'
    publishLocation: 'Container'
